server.port=8080

# Kubernetes service DNS
services.order-service.url=http://order-service:8083
services.user-service.url=http://user-service:8082
services.auth-service.url=http://auth-service:8081

# AUTH
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# USER
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://user-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

# ORDER
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=http://order-service:8083
spring.cloud.gateway.routes[2].predicates[2]=Path=/orders/**

# JWT
jwt.secret=${JWT_SECRET}

# ACTUATOR (??????????? ??? probes)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true